# ===== MediCore HMS — Service Discovery Configuration =====

server.port=8761

# Disable Eureka Client self-registration since this is the server registry itself
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Logging Configuration
logging.level.org.springframework.cloud=INFO
logging.level.com.netflix.eureka=INFO
logging.level.com.netflix.discovery=INFO
